title: "리체 팀블로그"
email: "tech@liche.co.kr"
description: "LICHE TEAM BLOG"
baseurl: ""
# url: "http://localhost:4000"
url: "https://blog.liche.dev"
github_username: "licheco"
lang: "ko_KR"
timezone: "Asia/Seoul"

permalink: /posts/:year-:month-:day-:title
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock

sass:
  sass_dir: _sass
