title: "liche Team Blog"
email: "official@liche.co.kr"
description: "Blog of liche Team"
baseurl: ""
url: "http://localhost:4000"
# url: "https://github.com/licheco/licheco.github.io"
github_username: "licheco"
lang: "ko_KR"
timezone: "Asia/Seoul"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock

sass:
  sass_dir: _sass
